name: Daily Commit

on:
  schedule:
    - cron: "13 3 * * *"  # Runs every day at 03:13 UTC
  workflow_dispatch:      # Optional: allows manual runs

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Step by 24f1001824@ds.study.iitm.ac.in
      run: |
        echo "Daily update: $(date -u)" >> daily-log.txt
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add daily-log.txt
        git commit -m "Daily commit on $(date -u)"
        git push
